<?php

return [
    'off'               => 0,

    'bold'              => 1,
    'dim'               => 2,
    'italic'            => 3,
    'underline'         => 4,
    'blink'             => 5,
    'inverse'           => 7,
    'hidden'            => 8,

    'bold off'          => 21,
    'dim off'           => 22,
    'italic off'        => 23,
    'underline off'     => 24,
    'blink off'         => 25,
    'inverse off'       => 27,
    'hidden off'        => 28,

    'black'             => 30,
    'red'               => 31,
    'green'             => 32,
    'yellow'            => 33,
    'blue'              => 34,
    'magenta'           => 35,
    'cyan'              => 36,
    'white'             => 37,
    'default'           => 39,

    'black bg'          => 40,
    'red bg'            => 41,
    'green bg'          => 42,
    'yellow bg'         => 43,
    'blue bg'           => 44,
    'magenta bg'        => 45,
    'cyan bg'           => 46,
    'white bg'          => 47,
    'default bg'        => 49,

    'bright black'      => 90,
    'bright red'        => 91,
    'bright green'      => 92,
    'bright yellow'     => 93,
    'bright blue'       => 94,
    'bright magenta'    => 95,
    'bright cyan'       => 96,
    'bright white'      => 97,
    'bright default'    => 99,

    'bright black bg'   => 100,
    'bright red bg'     => 101,
    'bright green bg'   => 102,
    'bright yellow bg'  => 103,
    'bright blue bg'    => 104,
    'bright magenta bg' => 105,
    'bright cyan bg'    => 106,
    'bright white bg'   => 107,
    'bright default bg' => 109,
];
